#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
	echo "Error: shandbox may not be run as root"
	exit 1
fi

if [ $# -lt 2 ]; then
	echo "Syntax: shandbox IMAGE EXEC"
	echo "IMAGE - Path to valid rootfs .img file"
	echo "EXEC - Command to execute in the container (e.g. /bin/sh)"
	exit 1
fi

if [ ! -f $1 ]; then
	echo "Error: $1 is not a file"
	exit 1
fi

sudo -v
while true; do
	sudo -n true
	sleep 60
	kill -0 "$$" || exit
done 2> /dev/null &

WORKDIR="$(mktemp -d)"
mkdir -p "$WORKDIR/rootfs" "$WORKDIR/changes" "$WORKDIR/work" "$WORKDIR/merged"

sudo mount -o loop,ro "$1" "$WORKDIR/rootfs"
if [ $? -ne 0 ]; then
	echo "Error: Image mount failed"
	rm -rf "$WORKDIR"
	exit 1
fi

cd "$WORKDIR"
unshare -muinprf .shandbox-container-setup "$2"

sudo umount "$WORKDIR/rootfs"
chmod +w "$WORKDIR/work/work"
rm -rf "$WORKDIR"
